version: '2'

services:
  bitbucket-server-lb:
    image: rancher/load-balancer-service
    links:
      - bitbucket
    ports:
      - ${Bitbucket_PORT}:7990

  bitbucket:
    image: atlassian/bitbucket-server:${BITBUCKET_VERSION}
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    links:
      - postgres
    labels:
      io.rancher.container.hostname_override: container_name

  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    stdin_open: true
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  bitbucket-data:
    driver: rancher-nfs
  postgres-data:
    driver: rancher-nfs