version: '2'

catalog:

  name: bitbucket
  version: 0.0.1
  description: Git Server
  questions:
    - variable: Bitbucket_PORT
      label: Port
      default: 80
      required: true
      type: int
    - variable: BITBUCKET_VERSION
      description: "Version of Bitbucket Server. Check https://www.atlassian.com/software/bitbucket/download?os=linux for current version."
      label: "Bitbucket Version"
      required: true
      default: "5.4.1"
      type: "string"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "bitbucket"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "bitbucket"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "bitbucket"
      type: "string"

services:

  bitbucket:
    scale: 1
    start_on_create: true

  bitbucket-server-lb:
    scale: 1
    load_balancer_config:
      haproxy_config: {}
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000

  bitbucket-data:
    scale: 1
    start_on_create: true

